apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: loki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: 3.4.2
    helm.sh/chart: loki-6.29.0
    prometheus.io/service-monitor: "true"
  name: loki-gateway-ext
  namespace: monitoring
spec:
  ports:
  - port: 31000
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
  type: LoadBalancer
status:
  loadBalancer: {}
