kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: nginx
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: nginx
  mode: all
  stressors:
    memory:
      workers: 1
      size: '50'
    cpu:
      workers: 0
      load: 1
  duration: 1m
