apiVersion: v1
kind: Service
metadata:
  labels:
    app: opentelemetry
    component: otel-collector
  name: otel-collector
  namespace: open-telemetry
spec:
  ports:
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: metrics
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    component: otel-collector
  sessionAffinity: None
  type: ClusterIP
